services:
  api:
    image: docker.io/bsnt/splitzy-backend:latest
    command: /start
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - splitzy
    restart: always
  frontend:
    image: docker.io/bsnt/splitzy-frontend:latest
    ports:
      - "8080:80"
    volumes:
      - /usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - api
    networks:
      - splitzy
    restart: always

  postgres-db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - splitzy
    restart: always

networks:
  splitzy:
    driver: bridge
volumes:
  postgres_data:
  static_volume:
  media_volume:
