# Generated by Django 5.2.7 on 2025-11-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
