# Generated by Django 5.2.7 on 2025-11-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_name_alter_membership_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
