# Generated by Django 5.2.7 on 2025-11-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_membership_name_alter_membership_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
