# Generated by Django 5.2.7 on 2025-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_invitation_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
