# Generated by Django 5.2.7 on 2025-12-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_groups_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.EmailField(max_length=254),
        ),
    ]
