name: MERN-Ecommerce Pipline

on:
  push:
    branches: ["compose-pipeline"] # The Event: trigger on every push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login to runner
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}

      - name: set tag for docker image
        run: echo "TAG_NAME=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: build docker image and push to dockerhub
        run: |
          docker compose -f docker-compose.prod.yml build
          docker tag $DOCKER_USER/$IMAGE_NAME:latest $DOCKER_USER/$IMAGE_NAME:$TAG_NAME
          docker push --all-tags $DOCKER_USER/$IMAGE_NAME
        env:
          DOCKER_REGISTRY: docker.io
          IMAGE_NAME: mern-image
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}

      - name: setting ssh
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY"> ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      - name: build react and rsync build and code to server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private_key" . $USER@$HOST:/home/esten/MERN-Ecommerce-Test/
          cd client
          npm ci 
          npm run build
          rsync -avz -e "ssh -i ~/.ssh/private_key" dist/ $USER@$HOST:/home/esten/build/
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ssh to server and deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_REGISTRY,DOCKER_USER,DOCKER_PSW,IMAGE_NAME
          script: |
            echo "$DOCKER_PSW" | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin
            docker pull $DOCKER_USER/$IMAGE_NAME:latest
            docker rm -f mern-server-container || true
            cd /home/esten/MERN-Ecommerce-Test/
            docker compose -f docker-compose.prod.yml up -d --no-build
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PSW: ${{ secrets.DOCKER_PASSWD}}
          IMAGE_NAME: mern-image
