# Generated by Django 5.2.7 on 2025-11-21 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0004_alter_membership_name_alter_membership_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesParticipants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('share', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.membership')),
            ],
        ),
    ]
