# Generated by Django 5.2.7 on 2025-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
