# Generated by Django 5.2.7 on 2025-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesparticipants',
            name='share',
        ),
        migrations.AddField(
            model_name='expensesparticipants',
            name='paid_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
