# Generated by Django 5.2.7 on 2025-11-22 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expensesparticipants_share_and_more'),
        ('groups', '0004_alter_membership_name_alter_membership_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedSettlements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment', models.FloatField(default=0.0)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='groups.membership')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='groups.membership')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
            ],
        ),
    ]
