# Generated by Django 5.2.7 on 2025-11-22 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_proposedsettlements'),
        ('groups', '0004_alter_membership_name_alter_membership_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBalances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.membership')),
            ],
        ),
    ]
