# Generated by Django 5.2.7 on 2025-11-23 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_groupbalances'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedsettlements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedsettlements',
            name='type',
            field=models.CharField(choices=[('P', 'Proposed'), ('A', 'Actual')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='proposedsettlements',
            name='expense_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses'),
        ),
    ]
