# Generated by Django 5.2.7 on 2025-11-23 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_proposedsettlements_created_at_and_more'),
        ('groups', '0004_alter_membership_name_alter_membership_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('P', 'Proposed'), ('A', 'Actual')], default='P', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='groups.membership')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='groups.membership')),
                ('expense_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
            ],
        ),
        migrations.DeleteModel(
            name='ProposedSettlements',
        ),
    ]
