# Generated by Django 5.2.7 on 2025-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_transactionrecords_delete_proposedsettlements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbalances',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
