# Generated by Django 5.2.7 on 2025-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_groupbalances_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbalances',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
