# Generated by Django 5.2.7 on 2025-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_groupbalances_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
