# Generated by Django 5.2.7 on 2025-11-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expenses_title'),
        ('groups', '0006_groups_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecords',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
        migrations.AddField(
            model_name='transactionrecords',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_by', to='groups.membership'),
        ),
    ]
