# Generated by Django 5.2.7 on 2025-11-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_alter_transactionrecords_recorded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_settled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrecords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionrecords',
            name='type',
            field=models.CharField(choices=[('P', 'Proposed'), ('A', 'Actual')], default='P', max_length=1),
        ),
    ]
