# Generated by Django 5.2.7 on 2025-12-02 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_expenses_added_by_expenses_is_settled_and_more'),
        ('groups', '0006_groups_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBalances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0)),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenses')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.membership')),
            ],
        ),
    ]
